---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authelia-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .LLDAP_LDAP_USER_PASS }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY | b64dec }}"
        AUTHELIA_JWT_SECRET: "{{ .AUTHELIA_JWT_SECRET }}"
        AUTHELIA_SESSION_SECRET: "{{ .AUTHELIA_SESSION_SECRET }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}"
        AUTHELIA_STORAGE_POSTGRES_DATABASE: &dbName authelia
        AUTHELIA_STORAGE_POSTGRES_HOST: &dbHost postgres-rw.database
        AUTHELIA_STORAGE_POSTGRES_PORT: &dbPort "5432"
        AUTHELIA_STORAGE_POSTGRES_USERNAME: &dbUser "{{ .AUTHELIA_STORAGE_POSTGRES_USERNAME }}"
        AUTHELIA_STORAGE_POSTGRES_PASSWORD: &dbPass "{{ .AUTHELIA_STORAGE_POSTGRES_PASSWORD }}"
        AUTHELIA_NOTIFIER_SMTP_DISABLE_REQUIRE_TLS: "false"
        AUTHELIA_NOTIFIER_SMTP_TLS_SERVER_NAME: "{{ .AUTHELIA_NOTIFIER_SMTP_TLS_SERVER_NAME }}"
        AUTHELIA_NOTIFIER_SMTP_HOST: "{{ .AUTHELIA_NOTIFIER_SMTP_TLS_SERVER_NAME }}"
        AUTHELIA_NOTIFIER_SMTP_PORT: "587"
        AUTHELIA_NOTIFIER_SMTP_SENDER: "{{ .AUTHELIA_NOTIFIER_SMTP_SENDER }}"
        AUTHELIA_NOTIFIER_SMTP_USERNAME: "{{ .AUTHELIA_NOTIFIER_SMTP_USERNAME }}"
        AUTHELIA_NOTIFIER_SMTP_PASSWORD: "{{ .AUTHELIA_NOTIFIER_SMTP_PASSWORD }}"
        AUTHELIA_DUO_API_DISABLE: "false"
        AUTHELIA_DUO_API_HOSTNAME: "{{ .AUTHELIA_DUO_API_HOSTNAME }}"
        AUTHELIA_DUO_API_INTEGRATION_KEY: "{{ .AUTHELIA_DUO_API_INTEGRATION_KEY }}"
        AUTHELIA_DUO_API_SECRET_KEY: "{{ .AUTHELIA_DUO_API_SECRET_KEY }}"
        AUTHELIA_NOTIFIER_SMTP_IDENTIFIER: "{{ .AUTHELIA_NOTIFIER_SMTP_IDENTIFIER }}"
        GRAFANA_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_OAUTH_CLIENT_SECRET }}"
        GRAFANA_REDIRECT_URI: "{{ .GRAFANA_REDIRECT_URI }}"
#        IMMICH_OAUTH_CLIENT_SECRET: "{{ .IMMICH_OAUTH_CLIENT_SECRET }}"
#        MINIFLUX_OAUTH_CLIENT_SECRET: "{{ .MINIFLUX_OAUTH_CLIENT_SECRET }}"
        WEAVEGITOPS_OAUTH_CLIENT_SECRET: "{{ .WEAVEGITOPS_OAUTH_CLIENT_SECRET }}"
#        GITEA_OAUTH_CLIENT_SECRET: "{{ .GITEA_OAUTH_CLIENT_SECRET }}"
        SECRET_DOMAIN: "{{ .CUSTOM_SECRET_DOMAIN }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_PORT: *dbPort
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: authelia
    - extract:
        key: cloudnative-pg
    - extract:
        key: lldap
