---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autobrr
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: autobrr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        AUTOBRR__DATABASETYPE: postgres
        AUTOBRR__POSTGRESDATABASE: &dbName autobrr
        AUTOBRR__POSTGRESHOST: &dbHost postgres-rw.database.svc.cluster.local
        AUTOBRR__POSTGRESUSER: &dbUser "{{ .AUTOBRR__POSTGRESUSER }}"
        AUTOBRR__POSTGRESPASS: &dbPass "{{ .AUTOBRR__POSTGRESPASS }}"
        AUTOBRR__POSTGRESPORT: "5432"
        AUTOBRR__SESSIONSECRET: "{{ .AUTOBRR__SESSIONSECRET }}"
        SECRET_DOMAIN: "{{ .CUSTOM_SECRET_DOMAIN }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
        WIREGUARD_PUBLIC_KEY: "{{ .WIREGUARD_PUBLIC_KEY }}"
        WIREGUARD_ADDRESSES: "{{ .WIREGUARD_ADDRESSES }}"
        VPN_SERVICE_PROVIDER: "{{ .VPN_SERVICE_PROVIDER }}"
        VPN_TYPE: "{{ .VPN_TYPE }}"
        VPN_ENDPOINT_IP: "{{ .VPN_ENDPOINT_IP }}"
  dataFrom:
    - extract:
        key: autobrr
    - extract:
        key: cloudnative-pg
