---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./gatus.yaml
configMapGenerator:
  - name: autobrr-configmap
    files:
      - config.toml=./config/config.toml
  - name: autobrr-dnsdist
    files:
      - ./config/dnsdist.conf
  - name: autobrr-resolv
    files:
      - ./config/resolv.conf
generatorOptions:
  disableNameSuffixHash: true
