---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-redis
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-redis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_REDIS_PASSWORD: "{{ .AUTHENTIK_REDIS__PASSWORD }}"
  dataFrom:
    - extract:
        key: Authentik
