apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Gyp+ak1+MczWI30OQ927P7Dkm088T/5f,iv:ec/Hp2uOiOqFDOgT508+mq8ljgfhWL5ssa1DV+5kmuU=,tag:h7kXmt5LaZmkrMCxdOt/9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18l9t76xcvq8tjg8mu38w7xpjswader4j0e3yxlpsyr96l7wdkc5src06l6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQ3JoeFcyaFNUL01pb3NX
            ZnBuUjJXRytwZWMvNnZrS2R0Zy9SYVAybUhvCmxHMGhGbHVPK3EzUStXQTgzK3NT
            MVMyT3lIUisyeGtSQ0xIZjgvQzkreG8KLS0tIHRpbXE2TnMvSE5hbHJhWENhOCs1
            b3RuNS83alpVdmtjY0lUam1VRmx6Q2cK956XvPnutQDfYR9M6+9qRPTUp6nhAysJ
            EwzpDubQ4tKB9JGfG2gWSEnWcHtU017F1b8p4/wwyvXjzfO4oVBU/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-19T01:57:15Z"
    mac: ENC[AES256_GCM,data:1CA1Q8M+TPyeymmO8XGJ8w9eYHNrXIMs1SV44eJJe414df36CA9LcfbJWrr4JcSiPoOmH72XVASzRfYd13iIdhmB3CTgGTllZVKl8y/BRnwMkrfj+h0dl4of/35lPEDD6ad82wGTMbv6LoREeWpoLZJRpEjnEC7KxLZ/4w+1BV0=,iv:ShGgayQX+JtE0dyjeQDVaq+gLfUwPixM5VcGNTCKqJk=,tag:Lq/pBfVc+RAFyGWU2x4U1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
