apiVersion: v1
kind: Secret
metadata:
    name: op-credentials
    namespace: one-password
type: Opaque
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:O/xzvjxG/+N9Artu6IsTRwVxVB6THACwc0g+ZxW8uryFpLjFaJlYGhCiY2Z32g88t/afXn4dKBcUgd0h646eFeCGXnp0+m8Uais9LachKnnOfWvKw1Wr8zW+Id8ACAGidCE0/F9Jtud8UGoodeksHl/gjgWagqs69Y9tIsDXt8djBi0/AnMKE5aDNHbwbM1dN5L4LxpKqlWFQ1ukYSYoks5Qq5DT6yFQ0ArbOgPwvz5uNqr+rmiPN6Qv/yhNgWPMTnELKvIOjwInQZlQiAjk0Swr86UskQahDzmdsCdNfZOS6QS55nJNxc1FVpUfbUnzTYIp8Q43uewTuPlZoT2N08M5Ixg90b2e2ZWSi7uzAZXfb8jaW+8KxlTNndHFhs4VMJ/8nG+IkRSvshcNR/nP9o+XZEcSroFsY+4ZNqFfKgo06H0F3h3STPzCMY0A4Q150hF7sWvYduY2DX0oeCSLgsvVn8zhtIyQUyakyYGFGPxyQids6NzpduyXwzn0QqfvjpZ852z8bcQfZkI5PMtTkJggwhFmCtxwvfm0clJDqlJYFTnWaRuboYTJkZmH2o59LiACmRXnaIDsivELpFNhZafZ9dpoO2rS/ORMAEbQKpHSVBjGgCiQCC2mni/6s+9z/e1dReT5aLz6GadzGtJ2j0wfXyb+X6Wmx2/XE34YvbJX3Mw0jFz2tze6ix/bYGOZHpll4LrePkQ0M61zEKK5B++xeEBkpLaZlbkvNk7nrSUvOz48OzgrWrahQBhfqSY3GrGj8+GGo0STomH0dybT37poC0ON3o9EBm6faUJVbheWMTf4uuRSgW88Z28WX97llkoisHK3ZHNYF+kmf1Hhwq8Drpg9oiRaw/Jt/GZBvob6P1qEwv3dis2eB0D7d8do09CTV0pyhI8ul/MJSPCK6mE8dzCPXpa/EZ4xoCoHxftx75bFzAJhdu1IRAsH+RxF/x6eKU725t/m6YDzsAOnsmQNm3SdEnmM2MyHATsfcynYQ7TsvvieabyLq8vj1LpKVSynn55IbVIpVTj+HvOJTdcWuGaeSpQrGtvZNkqV/Dmevx0YVHsCwccCTAzCPYwkx2gk+A9lwTW9K5sWPMNC1caOywb7dH2ov2ChobJIxksADmIcMj0fxZoFBWuhdSS4v6985YuOW5dVks8FdfJabWoEMK+HwuxUHzyvMY7qZ+Ppy4+BGiZPmKX/eIFTRymTi5Fp14m8GLuBfx8BVQSDqWCftxGUAGHFaorz+wozdgsIsYGNfaYkWgd7qlG8zoMzdxfBnPqDPWlityY+mVyGKYdshTyZGkJicdrurt0D4hMYmk/3O89CnNAe/+8AWwDIs4TE7P4k/poAeAc7mpIM5FC+3rUY43AQ5fmsUDUBOLGoR6U9xXU5OdHgTi0oatULJ8Q/Q+MXFHgVHMPdZ+SWH1AKUBPtk2apyA05T1Oo7w==,iv:sljkyLCIZms2FoCI7G4IX8oy5xTMXnlY9oSGwttb6UA=,tag:+X4o3kNhvRNXlul8+GVheA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18l9t76xcvq8tjg8mu38w7xpjswader4j0e3yxlpsyr96l7wdkc5src06l6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUlEvWDFycitxUk91QUhP
            UXBMOWgxY1dIaXFlWTNJQkdtUndGZUZpTVhJCmo3SjdtUmZ2UmpSUHBrSEY0NUVm
            S3B0N2N6NGtoUndRS3hISG9HZXBSb2sKLS0tIEZTYVQ4ZEU2V1lsQ3BiYWphKzMz
            Rmw2eWc2a0U5TXNsUHoyNTZrZ1YwSUkKD4d/D+MYaMY0MPphGacFA7Efn7wp5c31
            20KaDASZ6ScOdAEY9edydTt+DWg9arEVkcfSKz/7PKjyE30AT7sJbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-20T21:12:35Z"
    mac: ENC[AES256_GCM,data:Y5MFABwXJmK5RRYKx2VDF99L2GZ5ZPpk1pJlHqT0DN3Fd6Y2SGC+BPdGkAAPzGAZYbTIZy4dLqNPhDWv/qeinDGNVFYLKwbf8+VIYMWmWsMUSdBv8KRAsAAF7pg9vtxrQj+7w6tpsBiSn8AAvpztbKNfDmr69gk4w3IE+LLLodk=,iv:7kbRd+WuGz5l2MqwY7u1PThFco3/o0oTnsrGaRPWCX4=,tag:c9uu+EZeEyapA6Q1cib87Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
