---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vpn-gateway
  namespace: vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vpn-gateway
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
        WIREGUARD_ADDRESSES: "{{ .WIREGUARD_ADDRESSES }}"
        VPN_SERVICE_PROVIDER: "{{ .VPN_SERVICE_PROVIDER }}"
        VPN_TYPE: "{{ .VPN_TYPE }}"
        SERVER_CITIES: "{{ .SERVER_CITIES }}"
  dataFrom:
    - extract:
        key: vpn-gateway-vpnconfig
