
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  labels:
    # Avoid variable substitution of shell variables bellow
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu-helm-charts
        namespace: flux-system
  #See https://github.com/angelnu/helm-charts/blob/main/charts/apps/pod-gatewa/values.yaml

  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      # I am using dev version for testing - others should be using latest
      tag: latest
    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        # Use dev version
        pullPolicy: Always
        tag: latest
    DNS: 172.16.1.1
    service:
      vpn:
        enabled: true
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "192.168.40.12"
        externalTrafficPolicy: Cluster
        ports:
          shadowsocks:
            enabled: true
            port: 8388
        netshoot:
          enabled: true

    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: docker.io/qmcgaw/gluetun
            tag: latest
        env:
        - name: VPN_INTERFACE
          value: wg0
        - name: SHADOWSOCKS
          value: "on"
        - name: FIREWALL
          value: "off"
        - name: DOT
          value: "off"
        - name: SERVER_CITIES
          valueFrom:
            secretKeyRef:
              name: vpn-gateway
              key: SERVER_CITIES
        - name: WIREGUARD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: vpn-gateway
              key: WIREGUARD_PRIVATE_KEY
        - name: WIREGUARD_ADDRESSES
          valueFrom:
            secretKeyRef:
              name: vpn-gateway
              key: WIREGUARD_ADDRESSES
        - name: VPN_SERVICE_PROVIDER
          valueFrom:
            secretKeyRef:
              name: vpn-gateway
              key: VPN_SERVICE_PROVIDER
        - name: VPN_TYPE
          valueFrom:
            secretKeyRef:
              name: vpn-gateway
              key: VPN_TYPE
        securityContext:
          privileged: true
        networkPolicy:
          enabled: false

    podAnnotations:
      configmap.reloader.stakater.com/reload: vpn-gateway-pod-gateway
      secret.reloader.stakater.com/reload: vpn-gateway

    routed_namespaces:
      - downloads

    settings:
      # -- Traffic to these IPs will be send through the K8S gateway
      VPN_TRAFFIC_PORT: "51820"
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: wg0
      VPN_INTERFACE_MTU: "1400"
      VXLAN_ID: 43
      VXLAN_IP_NETWORK: 172.16.1
      VPN_LOCAL_CIDRS: "10.42.0.0/16 10.43.0.0/16 172.16.0.0/12 192.168.0.0/16"
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16 172.16.0.0/12 192.168.0.0/16"
