---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./gatus.yaml
commonLabels:
  app.kubernetes.io/name: echo-server
  app.kubernetes.io/instance: echo-server