apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:sYFdO9h+2dm/z1VETrpPwmq6Qt+avto+ZUA2ZFe6yJfotv7/c+8tt0j5kkBwafTyRL+PQlMngg3qxYb1,iv:sFAHuyeQCrs2PmzPllzbW9H42J+EzxPL3zTpqE0iiJ4=,tag:S3pV2NLM7uht7euUf6/3TQ==,type:str]
    username: ENC[AES256_GCM,data:kmkcdpc=,iv:Qie/3Su+T39CyTA1E0XgYqLG1J1LbI+OB+3ZPTj+Srs=,tag:I1JehdrEA3HW7UlU6EQU4Q==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18l9t76xcvq8tjg8mu38w7xpjswader4j0e3yxlpsyr96l7wdkc5src06l6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNlFtVzRUWWFxTSt3TCt0
            TnZBbXNaNi9HNUZXSWNKV3BFcXZ3RlVySzNvClJVSlhLc3QrTzZNWHJzUkhaK29q
            eUtWQVBORklrWFVKbEZ6MnhaTGppU3cKLS0tIDRZQTlQVkRtNGFseFdFbDVjSzZK
            bkx3eS9GSVBLUW9sNnkwRktXK21hUnMKcoXizX/i3Gwalt9qXqMVZRWtmSwzzJr+
            0J2HLg4+FckZHnt/eizxmVRLJmWagJp5MyvfLOoU0HBug63UbKw26w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T03:24:22Z"
    mac: ENC[AES256_GCM,data:AwuxR6Yf1Jt4QWZRkNGWYdDpjzwXMIMCeXEWSeJ28wWZjPTm7pphGNIcms2tBpG+t/KoOKBJSG7C2DyVHGsw973VxyY462I18BHjOanTps7bKbAbWdzbgk8Zvva7l8We/MyOI8/OdnO3BTup1zm6vNFB/+IpSgPTnjWikvkuUwE=,iv:/3yuy3MEQv5dUd+y9a6fHtPCZuf31iSXTMSLiyXbnHI=,tag:Ll4Iw42jkd9GOjZjaGZxbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
