---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-gatus-ep
  namespace: downloads
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: radarr
        group: external
        url: https://radarr.${SECRET_DOMAIN}
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
