---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./externalsecret.yaml
  - ./pvc.yaml
  - ./helmrelease.yaml
  - ./gatus.yaml
configMapGenerator:
  - name: radarr-configmap
    files:
      - ./scripts/pushover-notify.sh
  - name: radarr-dnsdist
    files:
      - ./config/dnsdist.conf
  - name: radarr-resolv
    files:
      - ./config/resolv.conf
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
