apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ye3+aYJZPsmKi9p+xhFmTI7DAur4wLS2,iv:8JCkTqty3+JXbBUC/T1hsZb2fuv0b3XcQecp+zYWjj8=,tag:+OUmrrjYPRjU3g4UHs6vMQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:wvJj6KjKolsfw6qTyBnW4EZhs23EAlUqSucC7KSD920Ic29Y,iv:ZOSr05wJm7w+KTbHv6OaKnJpeIMgt/YYJEsuy79MbEw=,tag:Y2LJCpVIZ4io5UclyvXIag==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:zt6PN0GbycNxAGworQ==,iv:7oqWT3ldX1wZcldFuU1VsDWkqEFoEhIe7Hd6iZ+H6hg=,tag:uNW5dvqJfj6jARMjWnk+kA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18l9t76xcvq8tjg8mu38w7xpjswader4j0e3yxlpsyr96l7wdkc5src06l6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTTA5dGVvM001dHV4VkNO
            TDJNWW14bzJoakZ4d1RENkROT1N6dUg3NUI4Ckk2N2hlZloyQTlqd0pod3lxeVFY
            d2tHbU5WL1ZSdmlsYkh5N3lURzd1OGMKLS0tIGV3R01GQzF4cHR4OGwxUlIzTkww
            UGRUVXhiQVZ4T1dZZDNPSTA1eEF1cVEK5qQKG/bRb8uD+zT8CnJRuOX/dJXdSgkm
            mQfb0h9oVRElpqJ+g6HMRygbGKfOLlv4bV8+Q1hc5qFjbIquIfdUqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-19T01:57:13Z"
    mac: ENC[AES256_GCM,data:l6Z5hr7wj5ETeAvpG418qkRuIDIrMK2bAIzqCcfe7cujzcJFcamv5MHg3BXr/LuCmpiyfBSXwGx0gdcynytw0AY/miMS+sFvP0xdxEByuZRXE9u1xti4Gf6Dq993xDCKjkgSw1WCkyraGN6HIVAsZtLZd8hFPigZTQxqWmvZ6bg=,iv:4YFvM5TMaIo+If6Yx3+3iXdLjqVAgi5xzhqCCd72uNc=,tag:XsRkZBwt7dJJ7L1qtbJ4qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
