apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:1WVrd/Z6A6K2xloJ5uIx1spJb2UE5sb0,iv:wf5E/idyd/iaxKVI4/vqPCmBMw87D2Y8HQUc6qP8YeI=,tag:CsQZGw3iqGfACMjzNfZNoA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:AP5Q8sQcCQa0dxPreR5m89PYgEXaDSJE+2HgAkGMY8u75LxU,iv:WCFRiij3Zei2SqW3DImUNGDGRUgAW577XIUcbcFqKFI=,tag:yrgsyVifmtuwnHba/0eD1w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:4QlSU6B7gwMcgVyocg==,iv:VMe0S8BDDGb42BKA6zOPvwHXkRCWSHkSLsBknaIu0Eg=,tag:a/pQ5lAymzhvnLWYKNGVlg==,type:str]
    SECRET_EMAIL_DOMAIN: ENC[AES256_GCM,data:5brPfNNE6bk=,iv:ptdS6rRYfacMjq6k7eCl5lqaZ5AAFx6p3/edsubrbtE=,tag:knQIAbSisLWRzcZHBn2G0A==,type:str]
    SECRET_SMTP_RELAY: ENC[AES256_GCM,data:poqT3EZgVkx5AqvCwNAKIF2V7xY=,iv:TRsbzJHgKUJvmprhjLU9K+WUrUkCE0NgRC+NqGynSnc=,tag:Mr+WirOB+Q4stLnmYGv7YQ==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:L9tgdijwQVrCWfLYSefnHQi98oHfKWd/1a0E1TRLuMo=,iv:rVrLJlSSoZetxNGy1waz+pbNSl9sxGJeBcrurUZJd5A=,tag:Ax+gGlZLWIWGKfEfrP8DpQ==,type:str]
    EABkeyID: ENC[AES256_GCM,data:2jDforQFqMx8lAwzM3HkF7QdgMKs4AO4K4+eUrpfXns=,iv:zZtmftHw+W96KrIYK/2dl4lb67ul5pDQwUvCFLiM1zY=,tag:iSQav6f0HLfo8DbKWRyDMA==,type:str]
    CERT_SERVER: ENC[AES256_GCM,data:REf0nxb49BVBKRwtK8wKdwB5ACVdCJYyfSA7tTyDITrlfveb6WHzuiiW,iv:ckzZaEYDOQ85ANL7FpLGyZV8KpvwaAOENseV/LTuQCQ=,tag:lVxb+mpML6iS9TAmL1GkJA==,type:str]
    KUBERNETES_DASH_TOKEN: ENC[AES256_GCM,data:NhlG0wlQ4TV/fu143p8Kn615KFHwwxIlUtISLRUa/ZjRcGS6mAtUXCiJ73OthC7LRStjc4mRTcZuELBxaYqPP4TYSxGRLG/SbOXt07eSBOaufokVzzyvYPgDCW5xGNTxUeS8KuCzyDclPat5CcqAGGqCyHsYl479OG51SBH3ETAzoWwTzX/c0Tw0NLrqdyP4lawAIA0YBFp/g7TqrJMrediQJ4o3THBKvFF3ICB5ct6Etqbnb/0szjISV5e41zO0xbn2GzJv5KwHoL8KwHntswKuxpSlpy7zJdbleejY7bKBIu6y0tuUKNzBJ7dMKjb3wroQ9KNFnRTzqAWcXtqJO9BIfZTlUPUBOWrPm3UtzZNAn/SMGhRbwoYJz+TLon5X6V5BsojWYh8UEWO0YyiRRewLwHbmI636YByh0Im+Jjmo9waHWPTy/ky+eH1tXfpbEzn6ORBPNmlU7+MeoXuuTn4PbMVb5VP2M5q6eQO7dDvyCj1/KNcJIpVykcijwM7HuaEMUS1KE4WzNtTnNBKYtCDAXzcGR/3fsUl5MVb5Lj0rWdmg4CIQQ0NIUyyKHkvRGenpSjeTm+Fiib8Cqp65VNib4dmfnkOf6a+hAEuVO3mLHXCJaD2HPiE0jL7lcavA/l9djYYtBHTb24ZmL8INewz2iqr5FzJNQddYfhSl0lBzwccR6LiDycXZ5VxzsaSl2Zo0/T4Ukb7y01nqMKRbWRKA5kJ4XAz2SCFxtBM0VE1nzJk9LulNfTIBKPIz5ItnTCqsPMW3PBLx3xGjIU8+h2NnjaPqRPL1FmVIgBlMLstD6Cv20ymEjhFZZxd+uT+6DJm+LB5X8qzMN6t3wW29Z2iJef94m/QsGbffCtZ84ZG1aKxZntsD3C68qLei0n3i8pIobJrAvTFc0zdxUSvwtYRV6oacqg+48RcTPlJsLfFHQrx6cPlmQZOpW3eLZQGK+SlQu7xLf8pQwWIwNZM4xfA/oeCFtlQ8RD10qWVSHR0Q7avkuiz0hQP0QUV72XwcFxo8ZnKQm+oUdc2N++W5UQQubUZAGZjDcBY06j4EvbVnF90KhsPbu6Egd/Ctp6LeQq/uKILIJNBuz1zJo43VGyoKq2BEaKfwBHQJwH+UqYIgwPWWjqgQPyNDiV+q8LxcGybudxAg8QyRIWm/KJkfNfOR2WBeIV3XgcEwaIV7Im9Xd1nQTkfW8LVBNkCjmwbW8xgXfGbUk+xS1JUK7Al0zrGSbCLkZo3SYVUW3FQqIgs=,iv:clRGa0a7TUCFFkltw2rpSGFsAB1YmpRc2TVbYJBAe90=,tag:ILDODkJlyxyiFIgQTB/gFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18l9t76xcvq8tjg8mu38w7xpjswader4j0e3yxlpsyr96l7wdkc5src06l6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTkdLb1M5WkYvOXloazRF
            R2dzMGp2V1NqcWZndU8wSm5PTUFmVW0vL0RjCkpYYXJsYUpiYVliNU1QelF0L09T
            TGRwL3BrVE1FS0pIc1hvRndlVWlJZ2MKLS0tIEhUeExVU1djaU1FdDRVNEVmZ09j
            ejZRVk1Ed2JmVThCNXN0bWRBV1VFZkEK9zqyPkOVPw6QfBNVptgS2cENiBB6KFPV
            iDZU7s7t770gxyrPdk6PFYCaiY4K0Ke2CFzYRlHw54A7LQl+pUgMeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-19T04:38:23Z"
    mac: ENC[AES256_GCM,data:SPkHjUgLqq006kl2sme1yhPAnMo9k83LrL5AHOnPfR1+RLj7jt5lgBd4BUm6Xwpmt7dbGixehPBlCkgUIMSDnlhlrTXo+trG1AZiCKCvFxZZ66Jwws4doGPF1JhcfXxqGpmPJ6EQDrgywwRkwwBp4k9fF22RclGVZtKKYfgreYs=,iv:PfJyvzECfu6Hcr2BbojX/6MSWwk8BCPrvNqvC6wzrGw=,tag:lO+gGlNadg9evi+tB3BbBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
