apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:thZDvnU7fdJQrLHm,iv:BoQrJuZL+9R9Q7JsQMONIaJxVjZHmDr5es/nE+XT1Zw=,tag:itdjM+4ORbmohkTXH/Uefw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18l9t76xcvq8tjg8mu38w7xpjswader4j0e3yxlpsyr96l7wdkc5src06l6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQ24vSFpSVlNCVGY4dDlY
            QjNQcFh4UDVjWjlPbk9sVEdLOUxQdVA1SUI0CktxV3ErV3hDNUtzZWVJYzluTVBT
            ZlJjaEVlMG9FY0tJUUlRN3p3NW96cTQKLS0tIFVMallQWW1TTVV2OFZlUVR2ZEtp
            aEVXRHF3cjVJSGRYWE9LSWFJREc3ODAKuubRJEDUkTACZNUvh30MjQqGec9fUa9o
            3otytHtLPv0Odfd6BY7IbEwEwWvYdrWXrVjGQdQt4qKvhOSCjyRHOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-18T16:39:10Z"
    mac: ENC[AES256_GCM,data:uJrVRpOJIMrRJ7jsLZmNTsaJTMGgFYY6vk0qcSFNPyRpjVB2DuEQk5Tldipt/Zinl6WPnK14qeZ41rTCjAwoF55lDfbYSLntFlW0LdKwPKeRNWHluqD/hWjIIdwNNBmtgDPugXUWdxJmmv3aKRnSFfw5eMqCaovMUtTa6tdN8bc=,iv:o/rS8l8oUKQrXrVs5TIelHxnVkGglG9c8PnNYPPvWpk=,tag:dwT140yMtQTqd8sFJdCaLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
