apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ok4mcIUk27CCPXb+WbA12jSBucrLz18k,iv:c/hNh/uqB4Uz3iZv3IdTzwdL1jbpCcPx7vJyktLZ6hw=,tag:xaixphv5YQeIIn1rymGFuQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:irMDPctqdWbhR16D1LNJVAFtDKFPK0qaYlfvqA6TDKC2Jzyk,iv:8lcLG3Lt4zXBpgjaOjLb+QjUHfqroHVC1JuOJL70okQ=,tag:/szYI6TenXBd5moTdpRlsA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZSkWF/TNyfMYOnK41w==,iv:9koi4oH83qdvZUZe+Qqra0kwYSHZwSYS/yeDQ7p8s28=,tag:FBLjChTUV7INH08Ly7IGvQ==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:ZeLkE1K/foDfeGUJTqven4esowLLVmUVIgk7OuFYk8k=,iv:uOzOMIP4MbYry3120BVEeXNUhBIREqPYn59Cl/XxI80=,tag:+7jrvdSu/5eeO3RLg6DkWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18l9t76xcvq8tjg8mu38w7xpjswader4j0e3yxlpsyr96l7wdkc5src06l6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NHpUc0dWMEZqY2hQS3lR
            UlBuK2w5SVY5VllwbSs2cGE4MW5LZzUrM213ClZEbXB6UVBUVVkzN3VHVVh5T1Q5
            MFFWMnRxVWQ1b0tMZ0p6b0FMQ0kxdVUKLS0tIEtQUElLSkhHUlBkMkFSVXFqRWxl
            cmtTMzB2WVBRem1idWlMU0lETFc3L0kKPu9Nae0VM2xeD8mioGNhKqZgWZ7axh9+
            JhFGIZ+iYponxWnuePeoLIN/GJqgisT5kkAymMkVvSZhTkLOyEOumg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-22T18:55:03Z"
    mac: ENC[AES256_GCM,data:DOaXbzDgD4KeoVrVRkS3/fHEuTrUMmiXTafF6iFa9wCssUVS6OBIdNca0d9OR7sRUxTEXAluaeMoF4+QE9PFWvh2xhLkgNjr8CTEY/ELVEFVLMbBW9CWOe938eTGlxr+ntLxe0blmCjX03d+DNTvmWQrI69rL15h3wsejP6btMQ=,iv:UOQbo6/ADQLxrDKANzTYwxrT5kDybtM3FX41Ba5G/zI=,tag:xU+lUb/1u5pfECLfX32zOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
