---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-gatus-ep
  namespace: media
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: plex
        group: external
        url: https://plex.${SECRET_DOMAIN}/web/index.html
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
