---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittools-reannounce
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: qbittorrent

  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 100

        containers:
          main:
            image:
              repository: ghcr.io/buroa/qbittools
              tag: v0.10.0@sha256:e700311562f88ca358c91e793494ce75ac5e355de45f3149ff03242170fd302c
            args:
              - reannounce
              - --process-seeding
              - -s
              - qbittorrent.downloads.svc.cluster.local
              - -p
              - "8080"
            resources:
              requests:
                memory: 250Mi
                cpu: 25m
              limits:
                memory: 500Mi

    service:
      main:
        enabled: false
