apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:991DLEiogV5SvKbhG1MSKU6Ck0gTYglDYWMkMwtep0f6yzvW,iv:gN1wlBuLw8Rzf4Dmo0mvcpdRETnVMMmpk8rPyd+xRVg=,tag:zSIcXASiGfSt7wdA+IES+g==,type:str]
    credentials.json: ENC[AES256_GCM,data:xT/2TXa3cBHUJ19IowLGcMH1sRiwoOtrTJaX5tFgP4Zgqy9S2Yyv4qKGURwdN5qwiPc/QyEcOob3p5OqBcpWAiDWr+Ct6uBboNVKAp+h8bzkTcCedRBJ1YurDl80GU8c+phRtuC7tEGxhZIm2JkZuJoHTxalvmz3hlzmtp8W4l4HIR+pMabyMCcaNH8Uinfh217NQUghKDz/QiuFb5g1fc6/Fo/HQ88wZy5ZFy+iiA==,iv:Es631OREAfhvrPuDa4EFJid1MFWCTvtpZOVNHtkoEfU=,tag:z8YGpqgMgLpydrKgyl/A8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18l9t76xcvq8tjg8mu38w7xpjswader4j0e3yxlpsyr96l7wdkc5src06l6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtb3RBRzNkNjlSOVJkUmpo
            V3AzbGV6WTl4dzd2SnRLQS9XU0lCOFRFbmhJCi9NTlNHaloyRUc5WGEvYUlwYVA0
            SlBOWmF4bUJRZ3BYTVFiTjVvU0psSTAKLS0tIDk1YUZIYlRYOVZ1c01wVWMwTHZG
            eEY1Wm5nbVZBZXE5ZlNJeEtXclJ2Q0kK4bK1XtXfLg9go+YdayBjCK2IMW39WW58
            1D6kVuFNPJQ7rvvoZWUnYCuJ7mZfcrUzCsRk/CjvWLEJqSAue5E2Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-19T01:57:15Z"
    mac: ENC[AES256_GCM,data:zeRyl17Yasq2Y+AOC4eHPEjFlLiWx1vP490vqX+QM1nMbCRnrZGxTcxItKRUsBsLJP4GtTIDu/XUpeynMrv0firFBkDAElx27FvN1F0B8/CEQI9GnkbnuRGQ/AcXyz00qRnh+f2yLEOCRSvMVLJ8s0eCBnLd/L+mQkxQFGQx+oA=,iv:shTT0Ad6jJItrhUHf45Fn3T/Rnu2VHCEy+eQPaSs6ZU=,tag:cBqZdqBviLhjYcQFyT7mDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
