---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: custom-awx-secret-key
  namespace: awx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: custom-awx-secret-key
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secret_key: "{{ .password}}"
  dataFrom:
    - extract:
        key: awx-data-secret