---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: rook-ceph
      version: v1.13.1
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    crds:
      enabled: true

    csi:
      provisioner:
        image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.3
      csiAddons:
        enabled: false
      cephFSKernelMountOptions: ms_mode=secure

      enableLiveness: true
      serviceMonitor:
        enabled: true

      kubeletDirPath: /var/lib/kubelet
      enableCSIHostNetwork: true
      pluginTolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"

      csiRBDProvisionerResource: |
        - name : csi-provisioner
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
        - name : csi-resizer
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
        - name : csi-attacher
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
        - name : csi-snapshotter
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
        - name : csi-rbdplugin
          resource:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 1Gi
        - name : csi-omap-generator
          resource:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 1Gi
        - name : liveness-prometheus
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi

      csiCephFSProvisionerResource: |
        - name : csi-provisioner
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
        - name : csi-resizer
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
        - name : csi-attacher
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
        - name : csi-snapshotter
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
        - name : csi-cephfsplugin
          resource:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 1Gi
        - name : liveness-prometheus
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi

    monitoring:
      enabled: true

    resources:
      requests:
        cpu: 1000m
        memory: 1G
      limits:
        memory: 2G
